-- public.activation_tokens definition

-- Drop table

-- DROP TABLE public.activation_tokens;

CREATE TABLE public.activation_tokens (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	expires_at timestamptz(6) NOT NULL,
	"token" varchar(255) NOT NULL,
	used bool NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT activation_tokens_pkey PRIMARY KEY (id),
	CONSTRAINT uk5jny0xpou62bqdjhkbw1c0qxd UNIQUE (token)
);


-- public.activation_tokens foreign keys

ALTER TABLE public.activation_tokens ADD CONSTRAINT fkgtry5rof27b5hdur1a11y0gsn FOREIGN KEY (user_id) REFERENCES public.users(id_user);


-- public.actividad_economica definition

-- Drop table

-- DROP TABLE public.actividad_economica;

CREATE TABLE public.actividad_economica (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion_negocio varchar(255) NULL,
	nombre_negocio varchar(255) NULL,
	telefono_negocio varchar(255) NULL,
	tiempo_actividad varchar(255) NULL,
	persona_id int8 NOT NULL,
	CONSTRAINT actividad_economica_pkey PRIMARY KEY (id),
	CONSTRAINT uktk8is98hs3pdj5bl046m0h877 UNIQUE (persona_id)
);


-- public.actividad_economica foreign keys

ALTER TABLE public.actividad_economica ADD CONSTRAINT fk9dgra9mdsw3qmyfm2c7we9jjl FOREIGN KEY (persona_id) REFERENCES public.persona_onboarding(id);


-- public.cooperativa definition

-- Drop table

-- DROP TABLE public.cooperativa;

CREATE TABLE public.cooperativa (
	id_cooperativa int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	calificacion float8 NULL,
	ciudad varchar(255) NULL,
	direccion varchar(255) NULL,
	id int8 NULL,
	logo_url varchar(255) NULL,
	monto_maximo_credito numeric(38, 2) NOT NULL,
	nombre varchar(255) NULL,
	pagina_web varchar(255) NULL,
	provincia varchar(255) NULL,
	telefono varchar(255) NULL,
	CONSTRAINT cooperativa_pkey PRIMARY KEY (id_cooperativa)
);


-- public.cooperativa_tasa definition

-- Drop table

-- DROP TABLE public.cooperativa_tasa;

CREATE TABLE public.cooperativa_tasa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activa bool NOT NULL,
	cooperativa_id int8 NOT NULL,
	fecha_actualizacion timestamp(6) NULL,
	fecha_creacion timestamp(6) NOT NULL,
	tasa_anual numeric(6, 3) NOT NULL,
	tipo_credito varchar(20) NOT NULL,
	CONSTRAINT cooperativa_tasa_pkey PRIMARY KEY (id),
	CONSTRAINT cooperativa_tasa_tipo_credito_check CHECK (((tipo_credito)::text = ANY ((ARRAY['MICROCREDITO'::character varying, 'CONSUMO'::character varying])::text[]))),
	CONSTRAINT uk_cooperativa_tasa_coop_tipo UNIQUE (cooperativa_id, tipo_credito)
);
-- public.direccion_onboarding definition

-- Drop table

-- DROP TABLE public.direccion_onboarding;

CREATE TABLE public.direccion_onboarding (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	barrio varchar(255) NULL,
	calle_principal varchar(255) NULL,
	canton varchar(255) NULL,
	numero varchar(255) NULL,
	provincia varchar(255) NULL,
	referencia_ubicacion varchar(255) NULL,
	tipo_vivienda varchar(255) NULL,
	persona_id int8 NOT NULL,
	CONSTRAINT direccion_onboarding_pkey PRIMARY KEY (id),
	CONSTRAINT direccion_onboarding_tipo_vivienda_check CHECK (((tipo_vivienda)::text = ANY ((ARRAY['PROPIA'::character varying, 'ARRENDADA'::character varying])::text[]))),
	CONSTRAINT uk7xc5cxb3gu8j79mbtr82tyfgp UNIQUE (persona_id)
);


-- public.direccion_onboarding foreign keys

ALTER TABLE public.direccion_onboarding ADD CONSTRAINT fkl3r5vsv1xqsketsxs1qdq8gml FOREIGN KEY (persona_id) REFERENCES public.persona_onboarding(id);

-- public.ingreso_egreso definition

-- Drop table

-- DROP TABLE public.ingreso_egreso;

CREATE TABLE public.ingreso_egreso (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	egreso_mensual float8 NULL,
	ingreso_mensual float8 NULL,
	persona_id int8 NOT NULL,
	CONSTRAINT ingreso_egreso_pkey PRIMARY KEY (id),
	CONSTRAINT uk5gth4afplf4c2jjjw287wbfuo UNIQUE (persona_id)
);


-- public.ingreso_egreso foreign keys

ALTER TABLE public.ingreso_egreso ADD CONSTRAINT fkn07yvqngy9ajl7duiip3kbbdt FOREIGN KEY (persona_id) REFERENCES public.persona_onboarding(id);

-- public.page_visits definition

-- Drop table

-- DROP TABLE public.page_visits;

CREATE TABLE public.page_visits (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	total_visits int8 NOT NULL,
	CONSTRAINT page_visits_pkey PRIMARY KEY (id)
);

-- public.password_reset_tokens definition

-- Drop table

-- DROP TABLE public.password_reset_tokens;

CREATE TABLE public.password_reset_tokens (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	expires_at timestamp(6) NOT NULL,
	"token" varchar(255) NOT NULL,
	used bool NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
	CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token)
);


-- public.password_reset_tokens foreign keys

ALTER TABLE public.password_reset_tokens ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id_user);
-- public.persona_onboarding definition

-- Drop table

-- DROP TABLE public.persona_onboarding;

CREATE TABLE public.persona_onboarding (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	apellidos varchar(255) NULL,
	cedula varchar(255) NULL,
	empresa_trabajo varchar(255) NULL,
	estado_civil varchar(255) NULL,
	estado_formulario varchar(255) NULL,
	fecha_nacimiento date NULL,
	fecha_registro timestamp(6) NULL,
	nombres varchar(255) NULL,
	ocupacion varchar(255) NULL,
	rol varchar(255) NULL,
	telefono varchar(255) NULL,
	solicitud_id int8 NOT NULL,
	CONSTRAINT persona_onboarding_estado_formulario_check CHECK (((estado_formulario)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'SOLICITADO'::character varying, 'COMPLETO'::character varying])::text[]))),
	CONSTRAINT persona_onboarding_pkey PRIMARY KEY (id),
	CONSTRAINT persona_onboarding_rol_check CHECK (((rol)::text = ANY ((ARRAY['SOLICITANTE'::character varying, 'CONYUGE_SOLICITANTE'::character varying, 'GARANTE'::character varying, 'CONYUGE_GARANTE'::character varying])::text[])))
);


-- public.persona_onboarding foreign keys

ALTER TABLE public.persona_onboarding ADD CONSTRAINT fkce6jfjtig1da6bj3hp72i9ref FOREIGN KEY (solicitud_id) REFERENCES public.solicitud_onboarding(id);


-- public.referencia_personal definition

-- Drop table

-- DROP TABLE public.referencia_personal;

CREATE TABLE public.referencia_personal (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre_completo varchar(255) NULL,
	parentesco varchar(255) NULL,
	telefono varchar(255) NULL,
	tipo varchar(255) NULL,
	persona_id int8 NOT NULL,
	CONSTRAINT referencia_personal_pkey PRIMARY KEY (id),
	CONSTRAINT referencia_personal_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PERSONAL'::character varying, 'FAMILIAR'::character varying])::text[])))
);


-- public.referencia_personal foreign keys

ALTER TABLE public.referencia_personal ADD CONSTRAINT fk3f5a2cdyal0xk5c9gh0qblcvb FOREIGN KEY (persona_id) REFERENCES public.persona_onboarding(id);

-- public.solicitud_cooperativa definition

-- Drop table

-- DROP TABLE public.solicitud_cooperativa;

CREATE TABLE public.solicitud_cooperativa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cooperativa_id int8 NOT NULL,
	estado varchar(30) NOT NULL,
	fecha_actualizacion timestamp(6) NULL,
	fecha_envio timestamp(6) NOT NULL,
	solicitud_id int8 NOT NULL,
	CONSTRAINT solicitud_cooperativa_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENVIADA'::character varying, 'SOLICITANDO_GARANTE'::character varying, 'RECHAZADA'::character varying, 'PRE_APROBADA'::character varying, 'ACEPTADA'::character varying])::text[]))),
	CONSTRAINT solicitud_cooperativa_pkey PRIMARY KEY (id),
	CONSTRAINT uk_solicitud_coop UNIQUE (solicitud_id, cooperativa_id)
);


-- public.solicitud_cooperativa foreign keys

ALTER TABLE public.solicitud_cooperativa ADD CONSTRAINT fkk4gsh2ixok5x2yyd647xyxaq9 FOREIGN KEY (solicitud_id) REFERENCES public.solicitud_credito(id);

-- public.solicitud_cooperativa_cotizacion definition

-- Drop table

-- DROP TABLE public.solicitud_cooperativa_cotizacion;

CREATE TABLE public.solicitud_cooperativa_cotizacion (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cuota_mensual numeric(38, 2) NOT NULL,
	fecha_calculo timestamp(6) NOT NULL,
	interes_total numeric(38, 2) NOT NULL,
	monto numeric(38, 2) NOT NULL,
	plazo_meses int4 NOT NULL,
	solicitud_cooperativa_id int8 NOT NULL,
	tasa_anual numeric(6, 3) NOT NULL,
	tasa_mensual numeric(10, 8) NOT NULL,
	tipo_credito varchar(255) NOT NULL,
	total_pagar numeric(38, 2) NOT NULL,
	CONSTRAINT solicitud_cooperativa_cotizacion_pkey PRIMARY KEY (id),
	CONSTRAINT solicitud_cooperativa_cotizacion_tipo_credito_check CHECK (((tipo_credito)::text = ANY ((ARRAY['MICROCREDITO'::character varying, 'CONSUMO'::character varying])::text[]))),
	CONSTRAINT uk_cotizacion_sc UNIQUE (solicitud_cooperativa_id)
);

-- public.solicitud_credito definition

-- Drop table

-- DROP TABLE public.solicitud_credito;

CREATE TABLE public.solicitud_credito (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	monto_solicitado numeric(38, 2) NOT NULL,
	ciudad varchar(255) NULL,
	id_cliente int8 NULL,
	tipo_credito varchar(20) NULL,
	email varchar(255) NOT NULL,
	estado varchar(255) NOT NULL,
	fecha_actualizacion timestamp(6) NULL,
	fecha_solicitud timestamp(6) NOT NULL,
	cedula varchar(255) NOT NULL,
	plazo_meses int4 NULL,
	provincia varchar(255) NULL,
	tipo varchar(255) NOT NULL,
	CONSTRAINT solicitud_credito_estado_check CHECK (((estado)::text = ANY ((ARRAY['CREADA'::character varying, 'ENVIADA'::character varying])::text[]))),
	CONSTRAINT solicitud_credito_pkey PRIMARY KEY (id),
	CONSTRAINT solicitud_credito_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['CREDITO'::character varying, 'INVERSION'::character varying])::text[]))),
	CONSTRAINT solicitud_credito_tipo_credito_check CHECK (((tipo_credito)::text = ANY ((ARRAY['MICROCREDITO'::character varying, 'CONSUMO'::character varying])::text[])))
);

-- public.solicitud_onboarding definition

-- Drop table

-- DROP TABLE public.solicitud_onboarding;

CREATE TABLE public.solicitud_onboarding (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	destino_credito varchar(255) NULL,
	estado varchar(255) NULL,
	fecha_creacion timestamp(6) NULL,
	usuario_id int8 NULL,
	CONSTRAINT solicitud_onboarding_estado_check CHECK (((estado)::text = ANY ((ARRAY['EN_PROCESO'::character varying, 'COMPLETADO'::character varying, 'SOLICITANDO_GARANTE'::character varying])::text[]))),
	CONSTRAINT solicitud_onboarding_pkey PRIMARY KEY (id)
);
-- public.user_pre_registration definition

-- Drop table

-- DROP TABLE public.user_pre_registration;

CREATE TABLE public.user_pre_registration (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city varchar(100) NULL,
	created_at timestamp(6) NOT NULL,
	first_name varchar(100) NOT NULL,
	identification varchar(30) NOT NULL,
	last_name varchar(100) NOT NULL,
	phone varchar(30) NULL,
	province varchar(100) NULL,
	user_id int8 NOT NULL,
	CONSTRAINT uk57p2dovguluiybc18niwx8pfa UNIQUE (user_id),
	CONSTRAINT user_pre_registration_pkey PRIMARY KEY (id)
);
-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id_user int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	cooperativa_id int8 NULL,
	created_at timestamp(6) NULL,
	email varchar(150) NOT NULL,
	"password" varchar(255) NULL,
	"role" varchar(20) NOT NULL,
	status varchar(30) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id_user),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT'::character varying, 'COOPERATIVE'::character varying, 'ADMIN'::character varying])::text[])))
);